package chatbot.task;

//@@author DenseLance-alt-reused
//Reused from code generated by GitHub Copilot
// with minor modifications (see AI.md)
/**
 * Set of task categories.
 */
public enum TaskCategory {
    TODO("T"),
    DEADLINE("D"),
    EVENT("E");

    private final String category;

    TaskCategory(String category) {
        this.category = category;
    }

    @Override
    public String toString() {
        return category;
    }
}
//@@author
