//@@author DenseLance-alt-reused
//Reused from code generated by GitHub Copilot
// with minor modifications (see AI.md)
package chatbot.parser;

import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

import chatbot.command.ByeCommand;
import chatbot.command.ClearCommand;
import chatbot.command.Command;
import chatbot.command.DeadlineCommand;
import chatbot.command.DeleteCommand;
import chatbot.command.EventCommand;
import chatbot.command.FindCommand;
import chatbot.command.ListCommand;
import chatbot.command.MarkCommand;
import chatbot.command.SortCommand;
import chatbot.command.ToDoCommand;
import chatbot.command.UnknownCommand;
import chatbot.command.UnmarkCommand;
import chatbot.exception.ChatbotException;

public class CommandParserTest {
    @Test
    void testParseByeCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("bye");
        assert command instanceof ByeCommand;
    }

    @Test
    void testParseClearCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("clear");
        assert command instanceof ClearCommand;
    }

    @Test
    void testParseListCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("list");
        assert command instanceof ListCommand;
    }

    @Test
    void testParseFindCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("find homework");
        assert command instanceof FindCommand;
    }

    @Test
    void testParseSortCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("sort");
        assert command instanceof SortCommand;
    }

    @Test
    void testParseMarkCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("mark 1");
        assert command instanceof MarkCommand;
    }

    @Test
    void testParseUnmarkCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("unmark 1");
        assert command instanceof UnmarkCommand;
    }

    @Test
    void testParseToDoCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("todo Buy groceries");
        assert command instanceof ToDoCommand;
    }

    @Test
    void testParseDeadlineCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("deadline Submit /by 1/1/2026 18:00");
        assert command instanceof DeadlineCommand;
    }

    @Test
    void testParseEventCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("event Meeting /from 1/1/2026 10:00 /to 1/1/2026 12:00");
        assert command instanceof EventCommand;
    }

    @Test
    void testParseDeleteCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("delete 1");
        assert command instanceof DeleteCommand;
    }

    @Test
    void testParseUnknownCommand() throws ChatbotException {
        Command command = CommandParser.parseCommand("unknown");
        assert command instanceof UnknownCommand;
    }

    @Test
    void testParseCommandCaseInsensitive() throws ChatbotException {
        Command cmd1 = CommandParser.parseCommand("bye");
        Command cmd2 = CommandParser.parseCommand("BYE");
        Command cmd3 = CommandParser.parseCommand("Bye");
        assert cmd1 instanceof ByeCommand;
        assert cmd2 instanceof ByeCommand;
        assert cmd3 instanceof ByeCommand;
    }

    @Test
    void testParseInvalidCharacterThrowsException() {
        assertThrows(ChatbotException.class, () -> CommandParser.parseCommand("todo test\\|invalid"));
    }
}
//@@author
